<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit212de84847ebc4367df4af02dd82bb42
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MessageBird\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MessageBird\\' => 
        array (
            0 => __DIR__ . '/..' . '/messagebird/php-rest-api/src/MessageBird',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit212de84847ebc4367df4af02dd82bb42::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit212de84847ebc4367df4af02dd82bb42::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit212de84847ebc4367df4af02dd82bb42::$classMap;

        }, null, ClassLoader::class);
    }
}
